version: '3.8'

services:
  web3-api:
    build:
      dockerfile: Dockerfile
      context: .
      target: local
    ports:
      - 3005:3005
    volumes:
      - ./:/app
      - node_modules:/app/node_modules  

volumes:
  node_modules: